FORMAT: 1A
HOST: http://agendacs.apiblueprint.org/

# Agenda-CS

Agenda-CS is a client-server cli that helps you manage your agendas.

# Group Users

Resources related to users in the API.

## User Collection [/v1/users]

### List All Users [GET]

+ Response 200 (application/json)

        {
            "Users": [
                {
                    "Name":"hza",
                    "Email":"123@qq.com",
                    "Phone":"567"
                },
                {
                    "Name":"hpz",
                    "Email":"789@qq.com",
                    "Phone":"333"
                },
                {
                    "Name":"kyj",
                    "Email":"222@qq.com",
                    "Phone":"444"
                }
            ],
            "Information": ""
        }

### Register User [POST]

+ Name (string) - The name of the user.
+ Password (string) - The password of the account.
+ Email (string) - The email of the user.
+ Phone (string) - The phone number of the user.

+ Request (application/json)

        {
            "Name":"hza",
            "Password":"123321",
            "Email":"123@qq.com",
            "Phone":"567"
        }

+ Response 201 (application/json)
    
        {
            "Information": ""
        }

### Delete User [DELETE]

+ Response 204

## User State [/v1/user/login]

### User Login [POST]

+ Name (string) - The name of the user.
+ Password (string) - The password of the account.

+ Request (application/json)

        {
            "Name":"hza",
            "Password":"123321"
        }

+ Response 201 (application/json)

        {
            "Information": "",
            "Name":"hza",
            "Email":"123@qq.com",
            "Phone":"567"
        }

## User State Reset [/v1/user/logout]

### User Logout [GET]

+ Response 200 (application/json)

        {
            "Information": ""
        }

# Group Meetings

Resources related to meetings in the API.

## Meeting Collection [/v1/meetings]

### Create New Meeting [POST]

+ Title (string) - The title of the meeting.
+ Participator (array[string]) - The participators of the meeting.
+ StartTime (string) - The start time of the meeting.
+ EndTime (string) - The end time of the meeting.

+ Request (application/json)

        {
            "Title":"agenda-cs",
            "Participator": [
                    "hza",
                    "hpz",
                    "kyj"
            ],
            "StartTime":"2017-10-28 09:30:00",
            "EndTime":"2017-10-28 10:30:00"
        }

+ Response 201 (application/json)

        {
            "Information": ""
        }


## Meeting Participators Addition [/v1/meeting/{title}/adding-participators]

+ Parameters
    + title:"default" (required, string) - Title of the Meeting in the form of an string

### Add Meeting Participators [PATCH]

+ request (application/json)

        {
            "Participator": [
                    "hza",
                    "hpz",
                    "kyj"
            ]
        }

+ Response 201 (application/json)

        {
            "Information": ""
        }


## Meeting Participators Deletion [/v1/meeting/{title}/deleting-participators]

+ Parameters
    + title:"default" (required, string) - Title of the Meeting in the form of an string

### Delete Meeting Participators [PATCH]

+ request (application/json)

        {
            "Participator": [
                    "hza",
                    "hpz",
                    "kyj"
            ]
        }

+ Response 201 (application/json)

        {
          "Information": ""
        }


## Query [/v1/users/query-meeting{?starttime,endtime}]

+ Parameters
    + starttime:"2017-10-28 09:30:00" (required, string) - Start time of Query range
    + endtime:"2017-10-28 10:30:00" (required, string) - End time of Query range

### Query Meetings [GET]

+ Response 200 (application/json)

        {
            "Meetings": [
                {
                    "Title":"agenda-cs",
                    "StartTime":"2017-10-28 09:30:00",
                    "EndTime":"2017-10-28 10:30:00",
                    "Host":"pml",
                    "Participator": [
                            "hza",
                            "hpz",
                            "kyj"
                    ]
                },
                {
                    "Title":"agenda-cs-second",
                    "StartTime":"2017-10-29 09:30:00",
                    "EndTime":"2017-10-29 10:30:00",
                    "Host":"pml",
                    "Participator": [
                            "hza",
                            "hpz",
                            "kyj"
                    ]
                }
            ],
            "Information": ""
        }

## Cancel [/v1/users/cancel-a-meeting/{title}]

+ Parameters
    + title:"default" (required, string) - Title of the Meeting in the form of an string

### Cancel a Meeting [DELETE]

+ Response 204

## Quitting [/v1/users/quit-meeting/{title}]

### Quit a Meeting [PATCH]

+ request (application/json)

        {
            "Title":"agenda-cs"
        }

+ Response 201 (application/json)

        {
          "Information": ""
        }


## Emptying [/v1/users/cancel-all-meeting]

### Clear a User's All Meetings [DELETE]

+ Response 204